version: '3'
services:
  spring-boot-app:
    build: ./DynatraceInternshipTaskBackend
    ports:
      - "8080:8080"
  react-app:
    build: ./DynatraceInternshipTaskFrontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/exchange
    depends_on:
      - spring-boot-app